### PR TITLE
Add some tests and fix 2 bugs

### PR DESCRIPTION
**Pull request by bcl**

### CODE REVIEW

**Comment by bcl** [comment]
@schwehr I'm pretty sure that 2nd commit is correct, maybe you have a reference for it I could add? IIRC multipart messages must be transmitted on the same channel.

**Comment by schwehr** [comment]
AIVDM/AIVDO (and all the other possible talkers) are defined in NMEA 4.0 and newer.  I bought a copy of 4.0 and the `Sequential message identifier` has to be the same for multipart messages.  It is implied but stated that each multipart message must happen on just one AIS channel (A or B traditionally with more channels coming).  You have to read ITU 1371 to see that the bits all have to come in one AIS VHF channel.  Ask more if it helps cause this stuff is definitely confusing and the specs are not well written.

**Comment by halmueller** [comment]
It's also implied by the existence of single-channel receivers like the SmartRadio SR161. If multipart messages could be split, single-channel receivers wouldn't work at all.

**Comment by schwehr** [comment]
Single channel receivers are not valid by any specs that I know of, so I wouldn't use that data point for a conclusion.  There are many receivers and even transceivers that don't handle valid messages

**Pull request merged**
