### PR TITLE
Add a maven setup.

### PR DESCRIPTION
**Pull request by schwehr**
First step towards continuous integration (CI) for Java in #17

Created with:

    mvn archetype:generate -DgroupId=com.aisparser -DartifactId=aisparser \
      -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4
      -DinteractiveMode=false

- Remove AllTests.java
- Move all sources to src/main/java/com/aisparser
- Move all working tests to src/test/java/com/aisparser
- Add pom.xml
  - Set version to 1.11-SNAPSHOT
  - Set url
  - Set to Java 8
  - Set pom.xml junit to 3

Try it with the following which makes the jars and tests things:

    cd java
    mvn package

### CODE REVIEW

**Comment by schwehr** [comment]
I need to fix up this PR before it can go in.  The version is wrong and it will take some merge work for other PRs

**Comment by bcl** [comment]
I've switched on travis-ci for this repo -- https://travis-ci.org/bcl/aisparser

**Comment by bcl** [comment]
Looks like a good start, If you can add travis support that would be great, and keeping the files in this PR as simple moves without changes is a good idea, it will make things easier to track as changes are added later.

**Comment by schwehr** [comment]
Once there is a base maven config, I will start on a travis config

**Comment by schwehr** [comment]
Now with Travis-CI testing of java!

The first build has to setup the cache of maven jar artifacts, but all following builds should go much faster.

https://travis-ci.org/bcl/aisparser/builds/508121458 setup the initial cache

**Comment by schwehr** [comment]
LGTM.  I think it's good to go

**Pull request merged**
